<a href="https://colab.research.google.com/github/Ash-Stat/An-Si-Hyun/blob/data/PCA%EC%B4%9D%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
#PCA실험
import pandas as pd
import numpy as np

In [56]:
a=pd.Series([5,5,4,2,3,4],index=np.arange(0,6))
b=pd.Series([2,2,3,4,5,6],index=np.arange(0,6))
c=pd.Series([4,4,4,4,4,3],index=np.arange(0,6))
d=pd.DataFrame({'예능' : a, '영화' : b, '아이돌' : c})
d

예능  영화  아이돌
0   5   2    4
1   5   2    4
2   4   3    4
3   2   4    4
4   3   5    4
5   4   6    3

In [83]:
#사이킷런의 PCA는 표준화를 해야만 값이 정확하다.
from sklearn.decomposition import PCA
pca=PCA() #요인개수 설정안하면 변수 갯수만큼의 축을 설정해줌
pca_result=pca.fit_transform(scaler_result)


In [84]:
print(' pc스코어 :\n', pca_result)

#1행의 1열은 첫번째 축 * 첫번째 변수들 이다.

#축이 두개고 변수의 개수가 6개이니까 총 PC스코어는 12개

 pc스코어 :
 [[-1.51292742 -0.59624575 -0.02575977]
 [-1.51292742 -0.59624575 -0.02575977]
 [-0.6342218   0.14849464  0.01011423]
 [ 0.64000431  1.62624713 -0.38332007]
 [ 0.72766898  0.90496335  0.51117051]
 [ 2.29240335 -1.48721362 -0.08644512]]


In [85]:
pca.components_ #고유값 벡터 
vector_mat=pd.DataFrame(pca.components_)
vector_mat

#가로가 축이다. 즉, 
#첫 번째 주성분은 -0.422094* x11 -0.720290 * x12 -0.550471 * x13 = P11이 되는 것이다  ( 첫번째 주성분의 첫 번째 객체의 PC점수)

0         1         2
0 -0.422094  0.720290 -0.550471
1 -0.782261  0.017484  0.622705
2  0.458152  0.693453  0.556075

In [86]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler_result=scaler.fit_transform(d)
scaler_result

array([[ 1.09321633, -1.11803399,  0.4472136 ],
       [ 1.09321633, -1.11803399,  0.4472136 ],
       [ 0.15617376, -0.4472136 ,  0.4472136 ],
       [-1.71791138,  0.2236068 ,  0.4472136 ],
       [-0.78086881,  0.89442719,  0.4472136 ],
       [ 0.15617376,  1.56524758, -2.23606798]])

In [87]:
-0.782261*1.09321633+( -1.11803399*0.017484)+(0.622705*0.4472136)

-0.59624606101529

In [89]:
pca.explained_variance_ #설명력 정도

array([2.23487137, 1.28170228, 0.08342635])

In [90]:
pca.explained_variance_ratio_ #설명력 비율

array([0.6207976 , 0.35602841, 0.02317399])

In [93]:
1.28170228/(2.23487137+1.28170228+0.08342635) #즉, explained_variance가 람다값이 되는 것 이다.

0.35602841111111116

0.9768260099999999