<a href="https://colab.research.google.com/github/Ash-Stat/An-Si-Hyun/blob/data/%EC%82%AC%EC%A7%84%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0%EC%8B%A4%ED%97%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
o=pd.Series([36.411958,36.412195,36.412466,36.412545,36.412783,36.412240])
a=pd.Series([127.393285,127.382247,127.382285,127.382321,127.393995,127.382258])    
o=pd.DataFrame(o)
a=pd.DataFrame(a)
a=pd.concat([a,o],axis=1)
a.columns=['longitude','latitude']
a

longitude   latitude
0  127.393285  36.411958
1  127.382247  36.412195
2  127.382285  36.412466
3  127.382321  36.412545
4  127.393995  36.412783
5  127.382258  36.412240

In [64]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
for x,y in zip(a['longitude'],a['latitude']):
  name=str(y)+' '+str(x)+'.jpg'
 
  img=cv2.imread(name,cv2.IMREAD_COLOR)
  
  plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
  plt.show()
  


[[[200 199 195]
  [200 199 195]
  [200 199 195]
  ...
  [202 199 195]
  [202 199 195]
  [202 199 195]]

 [[200 199 195]
  [200 199 195]
  [200 199 195]
  ...
  [202 199 195]
  [202 199 195]
  [202 199 195]]

 [[199 198 194]
  [199 198 194]
  [199 198 194]
  ...
  [201 198 194]
  [201 198 194]
  [201 198 194]]

 ...

 [[212 196 207]
  [212 196 207]
  [212 196 207]
  ...
  [211 193 206]
  [211 193 206]
  [210 192 205]]

 [[207 193 204]
  [207 193 204]
  [207 193 204]
  ...
  [206 189 202]
  [206 189 202]
  [206 189 202]]

 [[204 190 201]
  [203 189 200]
  [203 189 200]
  ...
  [206 189 202]
  [206 189 202]
  [206 189 202]]]
[[[ 48  62  68]
  [ 48  62  68]
  [ 48  62  68]
  ...
  [ 44  58  64]
  [ 44  58  64]
  [ 44  58  64]]

 [[ 51  65  71]
  [ 51  65  71]
  [ 51  65  71]
  ...
  [ 50  64  70]
  [ 50  64  70]
  [ 50  64  70]]

 [[ 48  62  68]
  [ 48  62  68]
  [ 48  62  68]
  ...
  [ 50  64  70]
  [ 50  64  70]
  [ 50  64  70]]

 ...

 [[101  90 106]
  [101  90 106]
  [101  90 106]
  ..

In [66]:
img=cv2.imread('36.412240 127.382258.jpg',cv2.IMREAD_COLOR)

#plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
#plt.show()

ValueError: ignored